cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

variables:
  MONGODB_URI: mongodb://mongo:27017/nodegoat

stages:
  - test
  - deploy

test:
  image: cypress/base:12
  stage: test
  services:
    - mongo
  script:
    - npm ci
    - npm run cy:verify
    - ./run.sh
    - npm run test:ci

deploy-staging:
  image: ruby:3.0
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip-cleanup
  only:
    - master
